# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".rls_exitfun", # <pipeline_on_exit>
  "%like%", # <rls_list_roles>
  "rolname", # <rls_list_roles>
  "privilege_type", # <rls_tbl>
  NULL
))
